---
title: "About Us| Tentang Kami"
---

### About the Site

This site was created to host teaching materials for R-Ladies Banda Aceh.

### About R-Ladies Banda Aceh

R-Ladies is a local chapter of R-Ladies Global ( https://www.rladies.org ), an organization that promotes gender diversity in the R community worldwide. We meetup in person or virtually to learn about the R programming language, algorithms and advanced tools.

Mengingat bahwa ini adalah komunitas R-Ladies pertama di Sumatra (dan di luar Jawa), serta keadaan COVID-19 yang berarti bahwa untuk sementara kegiatan akan dilakukan secara online, kami menerima peserta dari luar Banda Aceh.

R-Ladies welcomes members of all R proficiency levels, whether you're a new or aspiring R user, or an experienced R programmer interested in mentoring, networking & expert upskilling. Our community is designed to develop our members' R skills & knowledge through social, collaborative learning & sharing. Let's work together on supporting minority identity access to STEM skills & careers, the Free Software Movement, and contributing to the global R community! As a founding principle, there is no cost or charge to participate in any of our R-Ladies communities around the world. You can access our presentations, R scripts, and Projects on our GitHub account ( https://github.com/rladies ) and follow us on twitter ( https://twitter.com/RLadiesGlobal ) to stay up to date about R-Ladies news!
